service: DragonAuthorizer
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: us-west-2


functions:
  DragonAuthorizer:
    handler: handler.handler
